### ISSUE TITLE
Motors get stuck with certain recalculate functions

### ISSUE THREAD

**Issue by lachlan2k** [purduesigbots/libblrs#1]
I rewrote some of my code to include libmtrmgr, and noticed that my lift was moving incredibly slowly.
So I got my trusty LCD and printed out the values with motorGet, and noticed that the motor was only getting 29 power when it should've gone up to 127.

So here's the recalculate function I was using with a slew rate of 3.0:

```c
int applyLinearMotor(int input) {
    static const unsigned int trueSpeed[128] =
    { 0,6,7,7,8,8,8,9,9,9,
    10,10,10,10,11,11,11,11,11,11,
    12,12,12,12,12,12,12,13,13,13,
    13,13,13,13,14,14,14,14,14,15,
    15,15,15,16,16,16,16,17,17,17,
    17,18,18,18,19,19,19,19,20,20,
    20,21,21,21,21,22,22,22,23,23,
    23,23,24,24,24,25,25,25,26,26,
    26,26,27,27,27,28,28,28,29,29,
    30,30,31,31,32,32,33,33,34,35,
    36,36,37,38,39,40,41,43,44,45,
    47,48,50,52,54,56,58,60,63,66,
    68,71,74,78,81,85,127,127 };

    int output = trueSpeed[abs(input)] * sgn(input);

    return output;
}
```

The reason this happens is that motorGet returns 29, it adds slewRate * dT = 3.0 * 20, which is 89, and the 89th value in my array also happens to be 29, so the output never increases. The same collision problem happens with a slew rate of 1.0. when it gets to 13. As 13 + 1.0*20 = 33, the 33rd index of my array is 13.

Demonstration here: http://tpcg.io/woTx2I

What I did to circumvent this (this is an imperfect solution), is I removed the recalculate on line 68 https://github.com/purduesigbots/libblrs/blob/c2ac60dc060f1bd0d77280ca3799fde73e5a16a2/libmtrmgr/src/mtrmgr.c#L68

And added the recalculate to line 133, as seen here:
https://i.imgur.com/wTmkNru.png

This way, the recalculation is done once, when you request the value.

However, this solution only gives you the advantage of linear speed control, the slewing is not linear.

I'm unsure of what the "perfect" fix would be to get a linear slew increase.
Hope this helped.

**Comment by baylessj** [comment]
@tehkhop can you verify that this change fixes the issue you found?

**Comment by lachlan2k** [comment]
@baylessj I will be with the robot tomorrow. I'll report back within 24 hours. :)

**Comment by lachlan2k** [comment]
Awesome, works great! Closing the issue.
